version: '3.8'

services:
  # DB service
  postgres:
    image: postgres:15
    container_name: hw02_postgres
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # FastAPI service
  app:
    build: .
    container_name: hw02_fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
